/* Generated By:JJTree: Do not edit this line. ASTabstract_declarator.java */

package edu.vt.cs.sam.readers;

public class ASTabstract_declarator extends SimpleNode {
  public ASTabstract_declarator(int id) {
    super(id);
  }

  public ASTabstract_declarator(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
