/* Generated By:JJTree: Do not edit this line. ASTctor_definition.java */

package edu.vt.cs.sam.readers;

public class ASTctor_definition extends SimpleNode {
  public ASTctor_definition(int id) {
    super(id);
  }

  public ASTctor_definition(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
