/* Generated By:JJTree: Do not edit this line. ASTclass_specifier.java */

package edu.vt.cs.sam.readers;

public class ASTclass_specifier extends SimpleNode {
  public ASTclass_specifier(int id) {
    super(id);
  }

  public ASTclass_specifier(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
