/* Generated By:JJTree: Do not edit this line. ASTconversion_function_decl_or_def.java */

package edu.vt.cs.sam.readers;

public class ASTconversion_function_decl_or_def extends SimpleNode {
  public ASTconversion_function_decl_or_def(int id) {
    super(id);
  }

  public ASTconversion_function_decl_or_def(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
