/* Generated By:JJTree: Do not edit this line. ASTctor_initializer.java */

package edu.vt.cs.sam.readers;

public class ASTctor_initializer extends SimpleNode {
  public ASTctor_initializer(int id) {
    super(id);
  }

  public ASTctor_initializer(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
