/* Generated By:JJTree: Do not edit this line. ASTconditional_expression.java */

package edu.vt.cs.sam.readers;

public class ASTconditional_expression extends SimpleNode {
  public ASTconditional_expression(int id) {
    super(id);
  }

  public ASTconditional_expression(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
