/* Generated By:JJTree: Do not edit this line. ASTdtor_ctor_decl_spec.java */

package edu.vt.cs.sam.readers;

public class ASTdtor_ctor_decl_spec extends SimpleNode {
  public ASTdtor_ctor_decl_spec(int id) {
    super(id);
  }

  public ASTdtor_ctor_decl_spec(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
