/* Generated By:JJTree: Do not edit this line. ASThandler.java */

package edu.vt.cs.sam.readers;

public class ASThandler extends SimpleNode {
  public ASThandler(int id) {
    super(id);
  }

  public ASThandler(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
