/* Generated By:JJTree: Do not edit this line. ASTjump_statement.java */

package edu.vt.cs.sam.readers;

public class ASTjump_statement extends SimpleNode {
  public ASTjump_statement(int id) {
    super(id);
  }

  public ASTjump_statement(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
