/* Generated By:JJTree: Do not edit this line. ASTlabeled_statement.java */

package edu.vt.cs.sam.readers;

public class ASTlabeled_statement extends SimpleNode {
  public ASTlabeled_statement(int id) {
    super(id);
  }

  public ASTlabeled_statement(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
