/* Generated By:JJTree: Do not edit this line. ASTmember_declaration.java */

package edu.vt.cs.sam.readers;

public class ASTmember_declaration extends SimpleNode {
  public ASTmember_declaration(int id) {
    super(id);
  }

  public ASTmember_declaration(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
