/* Generated By:JJTree: Do not edit this line. ASTmember_declarator_list.java */

package edu.vt.cs.sam.readers;

public class ASTmember_declarator_list extends SimpleNode {
  public ASTmember_declarator_list(int id) {
    super(id);
  }

  public ASTmember_declarator_list(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
