/* Generated By:JJTree: Do not edit this line. ASTnamespace_decl.java */

package edu.vt.cs.sam.readers;

public class ASTnamespace_decl extends SimpleNode {
  public ASTnamespace_decl(int id) {
    super(id);
  }

  public ASTnamespace_decl(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
