/* Generated By:JJTree: Do not edit this line. ASTptr_to_member.java */

package edu.vt.cs.sam.readers;

public class ASTptr_to_member extends SimpleNode {
  public ASTptr_to_member(int id) {
    super(id);
  }

  public ASTptr_to_member(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
