/* Generated By:JJTree: Do not edit this line. ASTqualified_type.java */

package edu.vt.cs.sam.readers;

public class ASTqualified_type extends SimpleNode {
  public ASTqualified_type(int id) {
    super(id);
  }

  public ASTqualified_type(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
