/* Generated By:JJTree: Do not edit this line. ASTscope_override_lookahead.java */

package edu.vt.cs.sam.readers;

public class ASTscope_override_lookahead extends SimpleNode {
  public ASTscope_override_lookahead(int id) {
    super(id);
  }

  public ASTscope_override_lookahead(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
