/* Generated By:JJTree: Do not edit this line. ASTsuperclass_init.java */

package edu.vt.cs.sam.readers;

public class ASTsuperclass_init extends SimpleNode {
  public ASTsuperclass_init(int id) {
    super(id);
  }

  public ASTsuperclass_init(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
