/* Generated By:JJTree: Do not edit this line. ASTsimple_dtor_declarator.java */

package edu.vt.cs.sam.readers;

public class ASTsimple_dtor_declarator extends SimpleNode {
  public ASTsimple_dtor_declarator(int id) {
    super(id);
  }

  public ASTsimple_dtor_declarator(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
