/* Generated By:JJTree: Do not edit this line. ASTsimple_type_specifier.java */

package edu.vt.cs.sam.readers;

public class ASTsimple_type_specifier extends SimpleNode {
  public ASTsimple_type_specifier(int id) {
    super(id);
  }

  public ASTsimple_type_specifier(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
