/* Generated By:JJTree: Do not edit this line. ASTtemplate_default.java */

package edu.vt.cs.sam.readers;

public class ASTtemplate_default extends SimpleNode {
  public ASTtemplate_default(int id) {
    super(id);
  }

  public ASTtemplate_default(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
