/* Generated By:JJTree: Do not edit this line. ASTtemplate_id.java */

package edu.vt.cs.sam.readers;

public class ASTtemplate_id extends SimpleNode {
  public ASTtemplate_id(int id) {
    super(id);
  }

  public ASTtemplate_id(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
