/* Generated By:JJTree: Do not edit this line. ASTtry_block.java */

package edu.vt.cs.sam.readers;

public class ASTtry_block extends SimpleNode {
  public ASTtry_block(int id) {
    super(id);
  }

  public ASTtry_block(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
