/* Generated By:JJTree: Do not edit this line. C:\Users\adam\documents\school\independent_study\code\IndStudy\src\CPPParserTreeConstants.java */

package edu.vt.cs.sam.readers;

public interface CPPParserTreeConstants
{
  public int JJTTRANSLATION_UNIT = 0;
  public int JJTUSING_NAMESPACE = 1;
  public int JJTNAMESPACE_DECL = 2;
  public int JJTEXTERNAL_DECLARATION = 3;
  public int JJTVOID = 4;
  public int JJTPREPROCESSOR_OUTPUT = 5;
  public int JJTFUNCTION_DEFINITION = 6;
  public int JJTFUNC_DECL_DEF = 7;
  public int JJTLINKAGE_SPECIFICATION = 8;
  public int JJTDECLARATION = 9;
  public int JJTTYPE_MODIFIERS = 10;
  public int JJTDECLARATION_SPECIFIERS = 11;
  public int JJTSIMPLE_TYPE_SPECIFIER = 12;
  public int JJTSCOPE_OVERRIDE_LOOKAHEAD = 13;
  public int JJTSCOPE_OVERRIDE = 14;
  public int JJTQUALIFIED_ID = 15;
  public int JJTPTR_TO_MEMBER = 16;
  public int JJTQUALIFIED_TYPE = 17;
  public int JJTTYPE_QUALIFIER = 18;
  public int JJTSTORAGE_CLASS_SPECIFIER = 19;
  public int JJTBUILTIN_TYPE_SPECIFIER = 20;
  public int JJTINIT_DECLARATOR_LIST = 21;
  public int JJTINIT_DECLARATOR = 22;
  public int JJTCLASS_HEAD = 23;
  public int JJTCLASS_SPECIFIER = 24;
  public int JJTBASE_CLAUSE = 25;
  public int JJTBASE_SPECIFIER = 26;
  public int JJTACCESS_SPECIFIER = 27;
  public int JJTMEMBER_DECLARATION = 28;
  public int JJTMEMBER_DECLARATOR_LIST = 29;
  public int JJTMEMBER_DECLARATOR = 30;
  public int JJTCONVERSION_FUNCTION_DECL_OR_DEF = 31;
  public int JJTENUM_SPECIFIER = 32;
  public int JJTENUMERATOR_LIST = 33;
  public int JJTENUMERATOR = 34;
  public int JJTPTR_OPERATOR = 35;
  public int JJTCV_QUALIFIER_SEQ = 36;
  public int JJTDECLARATOR = 37;
  public int JJTDIRECT_DECLARATOR = 38;
  public int JJTDECLARATOR_SUFFIXES = 39;
  public int JJTFUNCTION_DECLARATOR_LOOKAHEAD = 40;
  public int JJTFUNCTION_DECLARATOR = 41;
  public int JJTFUNCTION_DIRECT_DECLARATOR = 42;
  public int JJTDTOR_CTOR_DECL_SPEC = 43;
  public int JJTDTOR_DEFINITION = 44;
  public int JJTCTOR_DEFINITION = 45;
  public int JJTCTOR_DECLARATOR_LOOKAHEAD = 46;
  public int JJTCTOR_DECLARATOR = 47;
  public int JJTCTOR_INITIALIZER = 48;
  public int JJTSUPERCLASS_INIT = 49;
  public int JJTDTOR_DECLARATOR = 50;
  public int JJTSIMPLE_DTOR_DECLARATOR = 51;
  public int JJTPARAMETER_LIST = 52;
  public int JJTPARAMETER_DECLARATION_LIST = 53;
  public int JJTPARAMETER_DECLARATION = 54;
  public int JJTINITIALIZER = 55;
  public int JJTTYPE_NAME = 56;
  public int JJTABSTRACT_DECLARATOR = 57;
  public int JJTABSTRACT_DECLARATOR_SUFFIX = 58;
  public int JJTTEMPLATE_HEAD = 59;
  public int JJTTEMPLATE_PARAMETER_LIST = 60;
  public int JJTTEMPLATE_DEFAULT = 61;
  public int JJTTEMPLATE_PARAMETER = 62;
  public int JJTTEMPLATE_ID = 63;
  public int JJTTEMPLATE_ARGUMENT_LIST = 64;
  public int JJTTEMPLATE_ARGUMENT = 65;
  public int JJTSTATEMENT_LIST = 66;
  public int JJTSTATEMENT = 67;
  public int JJTLABELED_STATEMENT = 68;
  public int JJTCOMPOUND_STATEMENT = 69;
  public int JJTELSE_STATEMENT = 70;
  public int JJTSELECTION_STATEMENT = 71;
  public int JJTITERATION_STATEMENT = 72;
  public int JJTJUMP_STATEMENT = 73;
  public int JJTTRY_BLOCK = 74;
  public int JJTHANDLER = 75;
  public int JJTEXCEPTION_DECLARATION = 76;
  public int JJTTHROW_STATEMENT = 77;
  public int JJTEXPRESSION = 78;
  public int JJTASSIGNMENT_EXPRESSION = 79;
  public int JJTCONDITIONAL_EXPRESSION = 80;
  public int JJTCONSTANT_EXPRESSION = 81;
  public int JJTLOGICAL_OR_EXPRESSION = 82;
  public int JJTLOGICAL_AND_EXPRESSION = 83;
  public int JJTINCLUSIVE_OR_EXPRESSION = 84;
  public int JJTEXCLUSIVE_OR_EXPRESSION = 85;
  public int JJTAND_EXPRESSION = 86;
  public int JJTEQUALITY_EXPRESSION = 87;
  public int JJTRELATIONAL_EXPRESSION = 88;
  public int JJTSHIFT_EXPRESSION = 89;
  public int JJTADDITIVE_EXPRESSION = 90;
  public int JJTMULTIPLICATIVE_EXPRESSION = 91;
  public int JJTPM_EXPRESSION = 92;
  public int JJTCAST_EXPRESSION = 93;
  public int JJTUNARY_EXPRESSION = 94;
  public int JJTNEW_EXPRESSION = 95;
  public int JJTNEW_TYPE_ID = 96;
  public int JJTNEW_DECLARATOR = 97;
  public int JJTDIRECT_NEW_DECLARATOR = 98;
  public int JJTNEW_INITIALIZER = 99;
  public int JJTDELETE_EXPRESSION = 100;
  public int JJTUNARY_OPERATOR = 101;
  public int JJTPOSTFIX_EXPRESSION = 102;
  public int JJTID_EXPRESSION = 103;
  public int JJTPRIMARY_EXPRESSION = 104;
  public int JJTEXPRESSION_LIST = 105;
  public int JJTCONSTANT = 106;
  public int JJTOPTOR = 107;
  public int JJTEXCEPTION_SPEC = 108;
  public int JJTEXCEPTION_LIST = 109;


  public String[] jjtNodeName = {
    "translation_unit",
    "using_namespace",
    "namespace_decl",
    "external_declaration",
    "void",
    "preprocessor_output",
    "function_definition",
    "func_decl_def",
    "linkage_specification",
    "declaration",
    "type_modifiers",
    "declaration_specifiers",
    "simple_type_specifier",
    "scope_override_lookahead",
    "scope_override",
    "qualified_id",
    "ptr_to_member",
    "qualified_type",
    "type_qualifier",
    "storage_class_specifier",
    "builtin_type_specifier",
    "init_declarator_list",
    "init_declarator",
    "class_head",
    "class_specifier",
    "base_clause",
    "base_specifier",
    "access_specifier",
    "member_declaration",
    "member_declarator_list",
    "member_declarator",
    "conversion_function_decl_or_def",
    "enum_specifier",
    "enumerator_list",
    "enumerator",
    "ptr_operator",
    "cv_qualifier_seq",
    "declarator",
    "direct_declarator",
    "declarator_suffixes",
    "function_declarator_lookahead",
    "function_declarator",
    "function_direct_declarator",
    "dtor_ctor_decl_spec",
    "dtor_definition",
    "ctor_definition",
    "ctor_declarator_lookahead",
    "ctor_declarator",
    "ctor_initializer",
    "superclass_init",
    "dtor_declarator",
    "simple_dtor_declarator",
    "parameter_list",
    "parameter_declaration_list",
    "parameter_declaration",
    "initializer",
    "type_name",
    "abstract_declarator",
    "abstract_declarator_suffix",
    "template_head",
    "template_parameter_list",
    "template_default",
    "template_parameter",
    "template_id",
    "template_argument_list",
    "template_argument",
    "statement_list",
    "statement",
    "labeled_statement",
    "compound_statement",
    "else_statement",
    "selection_statement",
    "iteration_statement",
    "jump_statement",
    "try_block",
    "handler",
    "exception_declaration",
    "throw_statement",
    "expression",
    "assignment_expression",
    "conditional_expression",
    "constant_expression",
    "logical_or_expression",
    "logical_and_expression",
    "inclusive_or_expression",
    "exclusive_or_expression",
    "and_expression",
    "equality_expression",
    "relational_expression",
    "shift_expression",
    "additive_expression",
    "multiplicative_expression",
    "pm_expression",
    "cast_expression",
    "unary_expression",
    "new_expression",
    "new_type_id",
    "new_declarator",
    "direct_new_declarator",
    "new_initializer",
    "delete_expression",
    "unary_operator",
    "postfix_expression",
    "id_expression",
    "primary_expression",
    "expression_list",
    "constant",
    "optor",
    "exception_spec",
    "exception_list",
  };
}
