/* Generated By:JJTree&JavaCC: Do not edit this line. CPPParserConstants.java */
package edu.vt.cs.sam.readers;

public interface CPPParserConstants {

  int EOF = 0;
  int PREPROCESSOR_OUTPUT_TOKEN = 11;
  int LCURLYBRACE = 12;
  int RCURLYBRACE = 13;
  int LSQUAREBRACKET = 14;
  int RSQUAREBRACKET = 15;
  int LPARENTHESIS = 16;
  int RPARENTHESIS = 17;
  int SCOPE = 18;
  int COLON = 19;
  int SEMICOLON = 20;
  int COMMA = 21;
  int QUESTIONMARK = 22;
  int ELLIPSIS = 23;
  int ASSIGNEQUAL = 24;
  int TIMESEQUAL = 25;
  int DIVIDEEQUAL = 26;
  int MODEQUAL = 27;
  int PLUSEQUAL = 28;
  int MINUSEQUAL = 29;
  int SHIFTLEFTEQUAL = 30;
  int SHIFTRIGHTEQUAL = 31;
  int BITWISEANDEQUAL = 32;
  int BITWISEXOREQUAL = 33;
  int BITWISEOREQUAL = 34;
  int OR = 35;
  int AND = 36;
  int BITWISEOR = 37;
  int BITWISEXOR = 38;
  int AMPERSAND = 39;
  int EQUAL = 40;
  int NOTEQUAL = 41;
  int LESSTHAN = 42;
  int GREATERTHAN = 43;
  int LESSTHANOREQUALTO = 44;
  int GREATERTHANOREQUALTO = 45;
  int SHIFTLEFT = 46;
  int SHIFTRIGHT = 47;
  int PLUS = 48;
  int MINUS = 49;
  int STAR = 50;
  int DIVIDE = 51;
  int MOD = 52;
  int PLUSPLUS = 53;
  int MINUSMINUS = 54;
  int TILDE = 55;
  int NOT = 56;
  int DOT = 57;
  int POINTERTO = 58;
  int DOTSTAR = 59;
  int ARROWSTAR = 60;
  int AUTO = 61;
  int BREAK = 62;
  int CASE = 63;
  int CATCH = 64;
  int CHAR = 65;
  int CONST = 66;
  int CONTINUE = 67;
  int _DEFAULT = 68;
  int DELETE = 69;
  int DO = 70;
  int DOUBLE = 71;
  int ELSE = 72;
  int ENUM = 73;
  int EXTERN = 74;
  int FLOAT = 75;
  int FOR = 76;
  int FRIEND = 77;
  int GOTO = 78;
  int IF = 79;
  int INLINE = 80;
  int INT = 81;
  int LONG = 82;
  int NEW = 83;
  int PRIVATE = 84;
  int PROTECTED = 85;
  int PUBLIC = 86;
  int REDECLARED = 87;
  int REGISTER = 88;
  int RETURN = 89;
  int SHORT = 90;
  int SIGNED = 91;
  int SIZEOF = 92;
  int STATIC = 93;
  int STRUCT = 94;
  int CLASS = 95;
  int SWITCH = 96;
  int TEMPLATE = 97;
  int THIS = 98;
  int TRY = 99;
  int TYPEDEF = 100;
  int UNION = 101;
  int UNSIGNED = 102;
  int VIRTUAL = 103;
  int VOID = 104;
  int VOLATILE = 105;
  int WHILE = 106;
  int OPERATOR = 107;
  int TRUETOK = 108;
  int FALSETOK = 109;
  int THROW = 110;
  int OCTALINT = 111;
  int OCTALLONG = 112;
  int UNSIGNED_OCTALINT = 113;
  int UNSIGNED_OCTALLONG = 114;
  int DECIMALINT = 115;
  int DECIMALLONG = 116;
  int UNSIGNED_DECIMALINT = 117;
  int UNSIGNED_DECIMALLONG = 118;
  int HEXADECIMALINT = 119;
  int HEXADECIMALLONG = 120;
  int UNSIGNED_HEXADECIMALINT = 121;
  int UNSIGNED_HEXADECIMALLONG = 122;
  int FLOATONE = 123;
  int FLOATTWO = 124;
  int CHARACTER = 125;
  int STRING = 126;
  int ID = 133;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;
  int IN_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "<PREPROCESSOR_OUTPUT_TOKEN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"throw\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "\"using\"",
    "\"namespace\"",
    "\"typename\"",
    "\"bool\"",
    "\"finally\"",
    "\"const_cast\"",
    "<ID>",
  };

}
